redhat-performance/badfish

badfish.py
tests/test_change_boot.py

Removed boiler plate by creating common methods for requests with:
- get_request()
- post_request()
- path_request()
- delete_request()
Added error handler for get_boot_devices

General refactoring

---

.travis.yml
badfish.py
tests/config.py
tests/test_base.py
tests/test_change_boot.py

This is the first of a series of improvements to accommodate badfish for multiple tenants.

Added find_systems_resource.

---

Dockerfile
README.md

Updated readme with instructions on how to run badfish via docker.

Added dockerfile.

---

badfish.py

Now we can pass the type of either director or foreman, for badfish
to configure the host to boot from the first interfaces defined in
the idrac_interfaces.yml for that type.
Interfaces file path is required.

Added boot-to-type optional argument.

---

badfish.py
tests/config.py

This will backport a few patches from the QUADS badfish library.
fixes: https://github.com/redhat-performance/badfish/issues/31

Backport fixes from QUADS badfish library.

---

.github/ISSUE_TEMPLATE/bug_report_or_issue.md
.github/ISSUE_TEMPLATE/feature_request_or_enhancement.md

Let's add issue templates for badfish.

implement issue templates

---

badfish.py
tests/config.py

closes:https://github.com/redhat-performance/quads/issues/309

feat: added reboot on boot change

---

README.md

Add docs for contributing and contact

Add docs for contributing and contact

---

badfish.py
config/idrac_interfaces.yml

merge @grafuls additional handler functionality from development

Merge error handler functionality

---

badfish.py
tests/test_base.py

added log message for interface not being a valid boot device

feat: added force optional argument for clear-jobs

---

badfish.py
config/idrac_interfaces.yml
tests/test_base.py

Merge latest set of commits from Development branch into master.

Merge Development Changes to Master

---

README.md

Adding small excerpt about using --force with --clear-jobs.
Toss the r640 Foreman interface string into char

doc:  --force with --clear-jobs and r640 string.

---

config/idrac_interfaces.yml

Update for fc640 strings

---

badfish.py

Pull in badfish fixes from development branch.

Merge Development Fixes to Master

---

badfish.py
config/idrac_interfaces.yml

Pull in @QuantumPosix changes to r740xd interface strings.

Sync Development with Master

---

README.md

Added `Setup` section for addressing new install instructions given the async requirements.

Fixes to readme 

---

README.md
src/badfish/badfish.py

Had to increase the number of retries for the new fc640 's to complete reboot on change boot order.

Added power state check plus increased reties by 30

---

src/badfish/badfish.py

Badfish does a lot more than managing interface boot order so making the
tool description more current.

minor: description field update.

---

setup.py
src/badfish/badfish.py

Merge latest development to upstream.

Development Sync to Upstream

---

src/badfish/badfish.py

fix: clear job queue regex
closes: https://github.com/redhat-performance/badfish/issues/120

feat: provide more accurate return codes

---

README.md
src/badfish/badfish.py

Returns a list of active jobs if any or the following msg if none:
"- INFO  - No active jobs found."

feat: Added --ls-jobs argparse.

---

README.md
src/badfish/badfish.py

feat: added VirtualMedia check and unmount
Fixes: https://github.com/redhat-performance/badfish/issues/125

RFE #125 - check/umount virtual media

---

README.md
src/badfish/badfish.py
tests/config.py

Added functionality for host type overrides on iDrac interfaces yaml.

Host type overrides

---

config/idrac_interfaces.yml

This adds some example per-rack overrides in our example
config/idrac_interfaces.yml

Add example per-rack overrides to Badfish.

---

src/badfish/badfish.py
tests/config.py
tests/test_base.py
tests/test_change_boot.py
tests/test_reboot_only.py

closes: https://github.com/redhat-performance/badfish/issues/118

fix: reboot-only for 740XD

---

README.md
config/idrac_interfaces.yml
src/badfish/badfish.py
tests/config.py
tests/test_base.py
tests/test_change_boot.py
tests/test_reboot_only.py

* Batch up latest changes in development branch and merge up

Merge Development Branch

---

config/idrac_interfaces.yml

added in new models (7425 and 7525) to the idrac_interfaces.yml

Adding changes for 7425 and 7525 boot order

---

README.md
config/idrac_interfaces.yml

* Add support for 7425 and 7525 boot order for @bengland2 and @QuantumPosix

Merge Development to Latest 

---

README.md
config/idrac_interfaces.yml

* Add a needed host-level override for differing systems.

Add more custom r640 overrides

---

README.md
config/idrac_interfaces.yml

* Sync development branch up
* We've move to quay.io

Move build refs to quay.io

---

README.md
src/badfish/badfish.py

This also resolves a back trace for r640s when set type is not available

feat: added get and set for SRIOV global mode

---

README.md
config/idrac_interfaces.yml
src/badfish/badfish.py

* Add support for SRIOV check/set, the ability to set is based on what the vendor allows so thus far that's only Dell that actually allows you to toggle this.

Sync Development up, add support for SRIOV check/set

---

src/badfish/badfish.py

closes: https://github.com/redhat-performance/badfish/issues/151

fix: --host arg gets interpreted as --host-list

---

src/badfish/badfish.py
tests/config.py
tests/test_base.py
tests/test_job_queue.py
tests/test_ls_interfaces.py
tests/test_ls_memory.py

Additionally added logic on test_base for multiple status codes
mocks on aiohttp.

tests: added test for additional coverage on clear-jobs

---

.editorconfig
setup.py
src/badfish/badfish.py

We were missing to include the helpers directory under the package
definition for setuptools.
Also refactored the logging logic to an independent logger for
easier imports when using BF as a python library.
Included .editorconfig for code styling.

fix: setup missing helpers include

---

README.md
config/idrac_interfaces.yml

* Add support for Dell R750 BIOS boot interface strings to `idrac_interfaces.yml`

Add Support for Dell R750.

---

requirements.txt
setup.py
src/badfish/badfish.py
tests/config.py
tests/test-requirements.txt
tests/test_base.py
tests/test_change_boot.py
tests/test_hosts_file.py
tests/test_screenshot.py

This generates a gif with all screenshots taken in a default period
of 3 minutes with intervals of 5 seconds.
This can be modified by passing --minutes and --interval.

feat: added --gif

---

README.md

* Update Foreman interface strings for our uses.

Doc:  Add Interface String Examples for Dell R650 / R750

---

CONTRIBUTING.md
README.md
src/badfish/badfish.py

Additionally added logic for cases where screenshot is not supported.

docs: Updated contributing guide

---

README.md

* Provide exact commands for toggling between UEFI and BIOS boot modes

doc: BIOS/EFI boot mode using --set-bios-attribute

---

src/badfish/badfish.py
tests/config.py
tests/test_base.py
tests/test_bios_attributes.py
tests/test_bios_password.py
tests/test_boot_to.py
tests/test_boot_to_mac.py
tests/test_boot_to_type.py
tests/test_change_boot.py
tests/test_check_boot.py
tests/test_execution.py
tests/test_firmware_inventory.py
tests/test_job_queue.py
tests/test_ls_interfaces.py
tests/test_ls_memory.py
tests/test_ls_processors.py
tests/test_ls_serial.py
tests/test_next_boot_pxe.py
tests/test_power.py
tests/test_reboot_only.py
tests/test_reset_bios.py
tests/test_reset_idrac.py
tests/test_screenshot.py
tests/test_sriov_mode.py
tests/test_virtual_media.py

[feat: added new command for listing server serial number](https://github.com/redhat-performance/badfish/pull/283/commits/456f883bff5e56ef07e3a7a471ec0fb7bf8e3200)
Closes: https://github.com/redhat-performance/badfish/issues/244
Closes: https://github.com/redhat-performance/badfish/issues/249

feat: change of authentication to tokenized

---

Dockerfile
Dockerfile_local
requirements.txt

added dockerfile_local for local development

fix: dockerfile new install instructions

---

src/badfish/badfish.py
tests/config.py
tests/test_screenshot.py

closes: https://github.com/redhat-performance/badfish/issues/288

fix: fixed bug when requesting gif from turned off server

---

config/idrac_interfaces.yml

minor update due to systems being moved around

new idrac_interfaces updates

---

config/idrac_interfaces.yml

* Update our `idrac_interfaces.yml` file to reflect changes in our environment.

Sync Development to Upstream

---

README.md

doc: remove markdown formatting typo

---

src/badfish/helpers/logger.py
src/badfish/main.py

closes: https://github.com/redhat-performance/badfish/issues/320

fix: output order via podman

---

README.md
src/badfish/helpers/async_lru.py
src/badfish/helpers/logger.py
src/badfish/main.py
tests/config.py
tests/test_virtual_media.py

Mounting, unmounting ISOs, and booting to virtual media (Virtual CD). Works on both Dell and Supermicro.

feat: rewrite and extension of features for virtual media

---

README.md
src/badfish/main.py
tests/config.py
tests/test_virtual_media.py

closes: https://github.com/redhat-performance/badfish/issues/228

feat: support for remote virtual media on nfs

---

README.md
src/badfish/main.py
tests/config.py
tests/test_reset_bios.py
tests/test_reset_bmc.py

closes: https://github.com/redhat-performance/badfish/issues/329

feat: Supermicro BMC reset

---

README.md
config/idrac_interfaces.yml

* Doc fixup for pip CLI installations.

Sync development changes

---

.github/workflows/issuetracker-webhook.yml
.github/workflows/push-event-webhook.yml

* This adds a GHA for sending webhook notifications on new issue creation.
* Tested in a testing gchat channel and it works.

feat: add chat webhooks for issue creation

---

.github/workflows/issuetracker-webhook.yml

* Further filtering of issue title for webhook notifications

Sync Development Branch to Upstream

---

src/badfish/main.py

Fix:  black linting for asyncio method spacing

---

README.md
src/badfish/main.py

* Black linting has been mad about some minor style-related spacing for some time
* Sync development -> upstream

Fix black linting in CI

---

.github/workflows/lint.yml
README.md

* Include docs update from @pablomh

Sync development to main branch

---

.github/workflows/issuetracker-webhook.yml

* Fixes issue brought to our attention by @AdnaneKhan in another repo.

Fix GHA vulnerability.

---

.github/workflows/issuetracker-webhook.yml
README.md

* Fix GHA vulnerability reported by @AdnaneKhan in another repository.

Merge Development to Main Branch

---

README.md

* We support EL9 and latest Fedora and rawhide too via RPM.

bump distribution versions supported.

---

.github/workflows/issuetracker-webhook.yml
README.md

* update supported EL distribution lists
* bump git to build new container as well

Sync Development to Upstream Branch

---

README.md

simplify fedora distribution list.

---

README.md

* Instead of listing each Fedora release and requiring us to edit them just simpify it.  GW

simplify fedora releases list

---

.github/ISSUE_TEMPLATE/pull_request_template.md

Closes: https://github.com/redhat-performance/badfish/issues/378

Added PR template

---

src/badfish/main.py
tests/config.py
tests/test_custom_interfaces.py

closes: https://github.com/redhat-performance/badfish/issues/380

fix: iDRAC8 / R630 boot_to

---

.gitignore
config/idrac_interfaces.yml
src/badfish/main.py
tests/config.py
tests/test_base.py
tests/test_bios_password.py
tests/test_context_manager.py
tests/test_ls_gpu.py

closes: https://github.com/redhat-performance/badfish/issues/447

fix: better session handling
