redhat-performance/badfish

README.md, config/idrac_interfaces.yml
It will be easier with a TOC in the README to quickly drill down or link
to specific commands, actions or documentation as things grow.
=> create TOC for README.

badfish.py, tests/config.py
This backports the following patches from the badfish QUADS library back
to upstream, standalone badfish and also updates the python tests.
https://github.com/redhat-performance/quads/commit/41f7390caf1106072552c0e7f3aa53812df48635
https://github.com/redhat-performance/quads/commit/43712d2cbdc0978c1dbd0c63f77775dffe513899
=> Backport QUADS fixes to upstream badfish.

README.md
* Correct documentation on behavior around using --boot-to and reboot
being required following this command.  This allows a bit better
control.
* Minor update on link resources.
fixes: https://github.com/redhat-performance/badfish/issues/43
=> Doc updates.

README.md, badfish.py, tests/config.py
Added --power-cycle which in contrast to reboot-only does a force
off instruction instead of a graceful reset.
Removed host status polling for reboot-only.
Fixes: https://github.com/redhat-performance/badfish/issues/40
=> Fix for double reboot.

README.md, badfish.py
if BootSources redfish API entrypoint is not available, none of
of the boot order operations can be executed on the host.
fixes: https://github.com/redhat-performance/badfish/issues/48
=> fix: better error messages for check-boot on non-supported

config/idrac_interfaces.yml
Update idrac_interfaces.yml key/value pairs to match recent changes to
interfaces in the ALIAS R&D environment.
Related-to: https://github.com/redhat-performance/badfish/issues/56
=> Update r740xd bios boot strings

badfish.py, tests/config.py
This is related to a patch submitted in related project
quads.  See:
https://review.gerrithub.io/c/redhat-performance/quads/+/486939
assuming the naming convention is followed as :
rack-uloc-blade-type.domain
where "blade" would be 000 for single system chassis systems,
while for bladecenters such as the fx2 chassis from Dell would
use values of "b01", "b02", etc.  This patch will extend the
idrac_interfaces lookups to differentiate between each blade
and will require a distinct entry for each for the "foreman"
and "director" types.  For example, if you have hosts with these
names:
f01-h20-b01-fc640.example.com
f01-h20-b02-fc640.example.com
Then you will also likely want to have the following entries
in your idrac_interfaces.yml file:
director_fc640_b01_interfaces: …
=> support added for blades

badfish.py
This fixes an unintended consequence of a previous patch
that parses the hostname in order to determine what to look
for in the idrac_interfaces.yml file.
Now to designate a blade (e.g. fc640), the hostname will need
to be of the form:
<x>-<y>-b0[0-9]-model
=> fix hostname parsing for blades

config/idrac_interfaces.yml
Changing the director interface for 740xd's due to nic3 being in front of non high speed interfaces causing foreman to boot to disk prior to High Speed nics when boot-to-type director.
=> Change 740xd director boot order to optimize PxE boot Interfaces

README.md, src/badfish/badfish.py
NOTE: All hosts can list the virtual media but unmount functionality
is only available for SuperMicro
$ src/badfish/badfish.py -H {HOST} -u root -p {PASS} --check-virtual-media
- INFO     - ID: CD1 - Name: Virtual Removable Media - ImageName: mymedia-read-only - Inserted: True
$ src/badfish/badfish.py -H {HOST} -u root -p {PASS} --unmount-virtual-media
- INFO     - Successfully unmounted all VirtualMedia
$ src/badfish/badfish.py -H {HOST} -u root -p {PASS} --check-virtual-media  
- WARNING  - No active VirtualMedia found
=> feat: added VirtualMedia check and unmount

README.md
* Folks need python3-devel if they are using the setuptools method of
installing badfish.
=> update README to mention python3-devel.

README.md
* It appears docker hasn't worked correctly for months but nobody
noticed since everyone uses podman.
* At least as far back as commit
https://github.com/redhat-performance/badfish/commit/5e7f5f2fa213d5c6d9939ce73cdfc87a21c6667f
we're getting an SSL error with docker, whereas podman does not have
this issue.
- DEBUG    - Cannot connect to host mgmt-server.example.com:443 ssl:False [Try again]
- ERROR    - Failed to communicate with server.
* At this point a pragmatic approach is to simply remove official
support for docker as it's not really being used anyway from our
userbase.  Podman works on the same platforms and has supplanted docker
in our uses.
* It doesn't make a lot of sense to continue stepping back into the git
commit history, locally building containers and testing beyond June …
=> Remove Listed Support for Docker

Dockerfile
Using "--no-cache-dir" flag in pip install ,make sure dowloaded packages
by pip don't cached on system . This is a best practise which make sure
to fetch ftom repo instead of using local cached one . Further , in case
of Docker Containers , by restricing caching , we can reduce image size.
In term of stats , it depends upon the number of python packages
multiplied by their respective size . e.g for heavy packages with a lot
of dependencies it reduce a lot by don't caching pip packages.
Further , more detail information can be found at
https://medium.com/sciforce/strategies-of-docker-images-optimization-2ca9cc5719b6
Signed-off-by: Pratik Raj <rajpratik71@gmail.com>
=> Use --no-cache-dir flag to pip in Dockerfiles, to save space

README.md
Update badfish capabilities in the docs.
Change to libera.chat #badfish and #quads, freenode unfortunately has
required accounts on irc.com which we feel is against the open and
anonymous/decentralized spirit of IRC.  We have moved to libera.chat.
=> doc: update capabilities, move to libera.chat

Dockerfile, Dockerfile_dev
limiting python alpine image to python 3.9
=> fix: async_lru not working with python3.10

README.md, rpm/.gitignore, rpm/python3-badfish.spec.tpl, tests/test-requirements.txt, tox.ini
Added instructions for RPM install plus usage as python library.
Slight refactor of rpm.spec.tpl.
Bumped version of pytest plus added python 3.10 environment to tox
testing.
=> docs: Added README instructions for RPM install

config/idrac_interfaces.yml
* Add idrac_interfaces.yml support for the Dell R750 BIOS boot device strings.
=> Add support for Dell R750

README.md
It's `BootMode` not `bootmode`
=> doc: typo in --set-bios-attribute example

README.md
* Although people can check exact syntax via `--set-bios-attribute` our verbatim command examples should always be correct.
=> doc: fix typo in --set-bios-attribute EFI example

README.md
* We can no longer support EL7 / Python <= 3.6
* List new features that have been added lately.
=> doc: Python 3.8 now required for non-container usage, list newer features.

Dockerfile, Dockerfile_local, README.md, requirements.txt
* Split out dockerfiles per environment
* Force a revision to the main Dockerfile as we were troubleshooting why quay.io doesn't seem to want to build us containers with new underlying code.
=> feat: split out dockerfiles

README.md
* Make it clear container is a valid 'installation' method for setup
* Mention RPM system package as a valid way of usage.
* sync upstream to development
=> doc: rework usage and setup sections.

README.md
* If RPM users want an `idrac_interfaces.yml` snag it from the repository instead and modify it to your liking.
=> doc: RPM won't come with idrac_interfaces.yml     

README.md
* Make it clear you need to manually reboot systems when using any of the `--boot-to` commands.
* RPM won't come with idrac_interfaces.yml, if RPM users want an `idrac_interfaces.yml` snag it from the repository example.
=> doc: --boot-to and RPM idrac_interfaces.yml

.github/workflows/lint.yml, .github/workflows/tox.yml
* Run GHA CI for PR's too
* Use `pull_request` instead of `pull_request_target` as tox and lint shouldn't need access to repo secrets.
reference:  https://securitylab.github.com/research/github-actions-preventing-pwn-requests/
=> feat: make tox/lint run on PR's too.

README.md
* Remove unneeded -t foreman command from --pxe.
* Explain a little more about what it does under the covers and scope.
=> doc: remove -t command from --pxe doc.

README.md, tests/test-requirements.txt
* Very minor README.md change to trigger CI and build us a new Fedora 38 RPM.
=> fix: bump README to trigger Fedora38 RPM build and update codecov version

README.md, src/badfish/main.py, tests/test-requirements.txt
fix: bump README to trigger Fedora38 RPM build and update codecov version (CI gets mad if not `2.1.13` now)
=> fix: bump README and update Codecov version, trigger Fedora 38 RPM build

.github/workflows/lint.yml, .github/workflows/tox.yml
* GHA's ubuntu-latest image now wants a minimum of Python 3.9 for CI.
=> GHA with ubuntu-latest wants at least Python 3.9 now

README.md
Because the idrac file won't be usually shared with other containers.
=> doc: README.md: Suggest private label in podman examples

README.md
* There is no such thing as EPEL for CentOS 8 and 9.
=> fix minor release distribution typo.

.gitignore, src/badfish/main.py, tests/config.py
closes: #354
The problem/bug from #354 was found to be present only on Dell systems. It appeared when forcing a one time boot to a specific device and virtual media. 
This functionality of commands using this approach was still right/valid (after rebooting the server it booted to the specified device), only the CLI output/log was displaying errors.
The cause of this was found to be a call of `create_bios_config_job()` right after `send_one_time_boot()` in the `boot_to()` function. The errors were happening because iDRAC already created the needed config job since the patch request was called with specified apply time to on reset (`payload_patch = {"@Redfish.SettingsApplyTime": {"ApplyTime": "OnReset"}}`).
Thus that call was removed since it wasn't needed and the functionality was tested …
=> fix: removed problematic call from boot_to()

.github/workflows/issuetracker-webhook.yml
You are using a variable which can be controlled by user input, and it may result in command execution on your runners, and secrets extraction by malicious actors.
Since the ${{ github.event.issue.title }} value can be controlled by the user who creates the issue, a malicious actor can inject system command that will run on the GitHub runner while the workflow is in progress and fetch sensitive data which stored there such as GitHub token with write permissions.
=> Sanitize variable which can be controlled by user input

config/idrac_interfaces.yml, src/badfish/helpers/logger.py, src/badfish/main.py, tests/config.py, tests/test_boot_to_type.py
closes: https://github.com/redhat-performance/badfish/issues/446
=> fix: default for custom device types on idrac_interfaces
